name: Create Pull Request

on:
  push:
    branches:
      - master
  schedule:
    - cron: '3 3 * * *'


jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Some changes" > some_file.txt  # например, создание или изменение файла

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b auto-branch
          git add .
          git commit -m "Automated changes"

      - name: Push changes
        run: git push --set-upstream origin auto-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: auto-branch
          title: "Automated Pull Request"
          body: "This is an automated pull request generated by GitHub Actions."
          labels: |
            automated
